Controllers/CollectionController.cs
using GardenArt.Core.Interfaces;
using GardenArt.Domain.Factory;
using GardenArt.Models;
using GardenArt.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GardenArt.Controllers
{
    public class CollectionController : Controller
    {
        //
        // GET: /Collection/
        IFactory factory = new Factory();
        public ActionResult Collections()
        {
            var mappedViewModel = factory.BuildAndMap<CollectionModel, CollectionListViewModel>();
            return View(mappedViewModel);
        }

        public ActionResult Collection(int id)
        {
            var mappedViewModel = factory.BuildAndMap<CollectionModel, CollectionDisplayViewModel>(id);
            return View(mappedViewModel);
        }


        public ActionResult CollectionView(int id)
        {
            var mappedViewModel = factory.BuildAndMap<SetModel, SetDisplayViewModel>(id);
            return View(mappedViewModel);
        }

    }
}

Controllers/ProductController.cs
using GardenArt.Core.Interfaces;
using GardenArt.Core.Interfaces.Mapper;
using GardenArt.Domain;
using GardenArt.Domain.Factory;
using GardenArt.Models;
using GardenArt.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GardenArt.Controllers
{
    public class ProductController : Controller
    {

        IFactory factory = new Factory();
        
        //
        // GET: /Product/

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Products()
        {
            //Jag mellanlagrade för syns skull, vill någon av er kan vi putta ner allt i return view.
            var mappedViewModel = factory.BuildAndMap<ProductModel, ProductDisplayViewModel>();
            return View(mappedViewModel);
            
        }

        [HttpPost]
        public ActionResult Article()
        {
            var mappedViewModel = factory.BuildAndMap<ProductModel, ArticleDisplayViewModel>();
            return View(mappedViewModel);  
        }

        public ActionResult Article(int id)
        {
            var mappedViewModel = factory.BuildAndMap<ProductModel, ArticleDisplayViewModel>(id);
            return View(mappedViewModel);
        }

        public ActionResult Collections()
        {
            return View();
        }


        public ActionResult Collection(int id)
        {
            var mappedViewModel = factory.BuildAndMap<CollectionModel, CollectionDisplayViewModel>(id);
            return View(mappedViewModel);
        }

       

        public ActionResult Category(int id)
        {
            var mappedViewModel = factory.BuildAndMap<CategoryModel, ProductCategoryViewModel>(id);
            return View(mappedViewModel);
        }
    }
}

Views/Collection/Collection.cshtml
@model GardenArt.ViewModels.CollectionDisplayViewModel

<!DOCTYPE html>
@{
    Layout = "~/Views/Layout/_LayoutOneColumn.cshtml";
    Page.Title = "Gardenart Sweden";
}


@section SideNavTop {
    <li>Kollektioner</li>
}

@section SideNav {

    @foreach (var item in Model.ListOfCollections)
    {
        <li>
            @Html.ActionLink(item.CollectionName, "Collection", new { id = item.CollectionID })
        </li>
    }

}

@section MobileNav {
    <dl class="sub-nav">
        @foreach (var item in Model.ListOfCollections)
        {
            <dd>
                @Html.ActionLink(item.CollectionName, "Collection", new { id = item.CollectionID })
            </dd>
        }

    </dl>
}

@section Headline {

    <h3>@Model.OneCollectionFromID.CollectionName</h3>

}


@section Content {
    <div id="articleimages">
        <ul class="example-orbit" data-orbit>
            @foreach (var item in Model.OneCollectionFromID.ImgList)
            {
              <li>
                <img src="@item" style="margin-bottom:20px" />
             </li>
            }
        </ul>
    </div>
    

    <p class="another_title">@Model.OneCollectionFromID.CollectionName</p>
    <p>@Model.OneCollectionFromID.Description </p>

    <a class="button secondary" href="@Url.Action("CollectionView", new { id = Model.OneCollectionFromID.CollectionID  })">
        Visa alla möbler från kollektionen @Model.OneCollectionFromID.CollectionName
    </a>
}

Views/Collection/CollectionView.cshtml
@model GardenArt.ViewModels.SetDisplayViewModel

<!DOCTYPE html>
@{
    Layout = "~/Views/Layout/_LayoutProduct.cshtml";
    Page.Title = "Gardenart";
}

@section SideNavTop {
    <li>Kollektioner</li>
}

@section SideNav {

    @foreach (var item in Model.ListOfCollections.OrderBy(x => x.ProductCategoryName))
    {
        <li>
            @Html.ActionLink(item.ProductCategoryName, "CollectionView", "Collection", new { id = item.ProductCategoryID }, null)
        </li>

    }

}

@section Headline {
    <h3>Alla våra möbler</h3>
}

@section Content {

    <ul class="small-block-grid-1 medium-block-grid-3">

        @foreach (var item in Model.ProductsInSet)
        {
            <li>

                <div class="product_box">

                    <div class="product_image">

                        <a href="@Url.Action("Article", "Product",new { id = item.ProductID })">
                            <img alt="@item.ProductName" id="@item.ProductID" src="@item.ImgUrl" />
                        </a>

                    </div>

                    <div class="product_text">
                        <span class="product_name">
                            @Html.ActionLink(item.ProductName +" " + item.ProductCategoryName, "Article", "Product", new { id = item.ProductCategoryID }, null)
                         </span>
                    </div>

                </div>

            </li>

        }

    </ul>
}

Views/Collection/Collections.cshtml
@model GardenArt.ViewModels.CollectionListViewModel

<!DOCTYPE html>
@{
    Layout = "~/Views/Layout/_LayoutProduct.cshtml";
    Page.Title = "Gardenart Sweden";
}

@section SideNavTop {
    <li>Kollektioner</li>
}

@section SideNav {

    @foreach (var item in Model.ListOfCollections)
    {
        <li>
            @Html.ActionLink(item.CollectionName, "Collection", new { id = item.CollectionID })
        </li>
    }
}

@section Headline {
    <h3>Kollektioner</h3>
    <p>

        Vi arbetar med aluminium som bas och med olika konstmaterial och härdat glas som accenter. Färgpaletten i grunden är stram i vitt, taupe, mocca, grått och svart och dessa färger går igen i alla våra material, vilket ger näst intill oändliga kombinations- möjligheter, dock med grundfärgerna som sammanhållande faktor.
    </p>
}
@section Content {

    <ul class="small-block-grid-1 medium-block-grid-2">

        @foreach (var item in Model.ListOfCollections)
        {

            <li>

                <div class="collection_box">
                   

                   
                    <div class="collection_image">
                        <a href="@Url.Action("Collection", new { id = item.CollectionID })">
                            <img alt="@item.CollectionName" src="@item.ImgUrl" />
                        </a>
                    </div>

                    <div class="collection_text">
                        <span class="collection_name">@Html.ActionLink(item.CollectionName, "Collection", new { id = item.CollectionID })</span>
                    </div>

                </div>


            </li>


        }

    </ul>
}